name: build
on: push
permissions:
  packages: write
jobs:
  go-runner:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: |-
        set -o errexit
        set -o nounset
        set -o pipefail

        cd go-runner
        CONFIG=go1.16-buster \
        IMAGE_VERSION=v2.3.1-go1.16.15-buster.0 \
        GO_MAJOR_VERSION=1.16 \
        OS_CODENAME=buster \
        REVISION=0 \
        GO_VERSION=1.16.15 \
        DISTROLESS_IMAGE=static-debian10 \
        REGISTRY=ghcr.io/zhouhaibing089/k8s/build-image \
        make manifest
  debian-base:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: |-
        set -o errexit
        set -o nounset
        set -o pipefail

        cd debian-base
        CONFIG=buster \
        IMAGE_VERSION=buster-v1.9.0 \
        REGISTRY=ghcr.io/zhouhaibing089/k8s/build-image \
        make push-manifest
